# DockerFile to compile ACS 2017.02 using ExtProd and Tools from RPMs
FROM centos:centos7

MAINTAINER CSRG <leonardo.pizarro@usm.cl>

#Installing dependencies
RUN curl https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -o /etc/yum.repos.d/epel-apache-maven.repo
RUN curl http://repo.csrg.cl/acs-cb.repo -o /etc/yum.repos.d/acs-cb.repo
RUN yum -y install epel-release centos-release-scl
RUN yum install -y ACS-ExtProds ACS-ExtJars
RUN yum install -y gcc gcc-c++ emacs antlr expat expat-devel cppunit cppunit-devel swig loki-lib log4cpp shunit2 castor hibernate3 xerces-c xerces-c-devel xerces-j2 time ksh rh-java-common-PyXB python-pmw-1.3.2 pexpect PyXML pychecker apache-commons-lang junit javassist geronimo-jta mockito mysql-connector-java objenesis xmlunit procmail tkinter
RUN yum install -y git rpm-build tar svn vim

# Copy tao_ifr_service
RUN curl http://repo.csrg.cl/Sources/tao_ifr_service -o /usr/local/bin/tao_ifr_service
#Creating rpm user
RUN adduser -U almabuild
USER almabuild

#Download rpm repo
RUN git clone --depth 1 -b master https://github.com/csrg-utfsm/acscb.git ~/ACS-2017.02/
# pythfilter, aka SOURCE1
RUN curl https://raw.githubusercontent.com/tmbdev/pylinda/master/linda/doc/pythfilter.py -o ~/ACS-2017.02/LGPL/Tools/extpy/src/pythfilter.py
# Add bash_profile to bashrc
RUN echo "source ~/ACS-2017.02/LGPL/acsBUILD/config/.acs/.bash_profile.acs" >> ~/.bashrc
# Source env vars installed by ExtProds RPM in profile.d to "clean" values set by bash_profile.acs
RUN echo "source /etc/profile.d/acscb.sh" >> ~/.bashrc &&\
    echo "source /etc/profile.d/mico.sh" >> ~/.bashrc &&\
    echo "source /etc/profile.d/jacorb.sh" >> ~/.bashrc &&\
    echo "source /etc/profile.d/ant.sh" >> ~/.bashrc &&\
# overrides ACE_ROOT
    echo "source /etc/profile.d/ace-devel.sh" >> ~/.bashrc &&\
    echo "source /etc/profile.d/apache-maven.sh" >> ~/.bashrc &&\
    echo "source /etc/profile.d/mpc.sh" >> ~/.bashrc &&\
    echo "source /etc/profile.d/tao-devel.sh" >> ~/.bashrc &&\
    echo 'SWIG_ROOT="/usr/share/swig" ' >> ~/.bashrc
# Source other stuff to clean more what bash_profile has done
# CHECK CLASSPATH
RUN echo 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk' >> ~/.bashrc &&\
    echo 'ACSDATA="/alma/2017.02/acsdata"'  >> ~/.bashrc &&\
    echo 'ACSROOT="/alma/2017.02/ACSSW"' >> ~/.bashrc &&\
    echo 'ALMASW_INSTDIR="/alma/ACS-2017.02' >> ~/.bashrc &&\
    echo 'ACS_CDB="$ACSDATA/config/defaultCDB"' >> ~/.bashrc &&\
    echo 'ACS_INSTANCE="0"' >> ~/.bashrc &&\
    echo 'ACS_STARTUP_TIMEOUT_MULTIPLIER="2"' >> ~/.bashrc
# It should be just /tmp
RUN echo 'ACS_TMP="/alma/2017.02/acsdata/tmp/$HOSTNAME"' >> ~/.bashrc &&\
    echo 'IDL_PATH="-I/alma/2017.02/ACSSW/idl -I/usr/src/debug/ACE_wrappers/TAO/orbsvcs/orbsvcs -I$TAO_ROOT/orbsvcs -I$TAO_ROOT -I/usr/include/orbsvcs -I/usr/include/tao" ' >> ~/.bashrc &&\
    echo 'LD_LIBRARY_PATH="/alma/2017.02/ACSSW/idl:/usr/lib64/:$ACSROOT/tcltk/lib:/usr/local/lib64:/usr/local/lib"' >> ~/.bashrc &&\
    echo 'GNU_ROOT="/usr"' >> ~/.bashrc &&\
    echo 'PYTHONPATH="/usr/lib64/python2.7/site-packages:/usr/lib/python2.7/site-packages:/opt/rh/rh-java-common/root/usr/lib/python2.7/site-packages/:/home/almamgr/2017.02/ACSSW/lib/python/site-packages:/usr/local/lib/python/site-packages/"' >> ~/.bashrc &&\
    echo 'PYTHON_ROOT="/alma/2017.02/Python"' >> ~/.bashrc &&\
    echo 'PYTHONINC="/usr/include/python2.7"' >> ~/.bashrc &&\
    echo 'PATH="$PATH:/alma/2017.02/tctlk/bin:/alma/2017.02/JacORB/bin:$GNU_ROOT/bin:/alma/2017.02/ACSSW/bin"' >> ~/.bashrc

ENV MAKE_NOSTATIC=yes
ENV MAKE_NOIFR_CHECK=on
ENV MAKE_PARS=" -j 2 -l 2 "
# clean before
RUN /bin/bash -c "source ~/.bashrc" && cd $ACSROOT && find -name "*.o" | xargs rm -rf

#RUN /bin/bash -c "source ~/.bashrc" && cd ~/ACS-2017.02/ && make
# Clean
#RUN /bin/bash -c "source ~/.bashrc" && cd $ACSROOT && find -name "*.o" | xargs rm -rf
USER root
