#!/bin/bash
#
# chkconfig: 35 90 12
# description: ACS CB Manager service
#
# Get function from functions library
. /etc/init.d/functions

# Create files as root
acscbFolder="/var/run/acscb"
mkdir -p $acscbFolder
IORFILE="daemonManagerImp.ior"
PIDFILE="daemonManagerImp.pid"
touch $acscbFolder/$IORFILE
touch $acscbFolder/$PIDFILE
lockfile="/var/lock/subsys/acscbDaemonManagerImp"

chown almaproc:root $acscbFolder/$IORFILE
chown almaproc:root $acscbFolder/$PIDFILE

user=almaproc
# ACS Source Environment file
. /etc/acscb/bash_profile.acs.old

# Start the service 
start() {
        echo "Starting acscbDaemonManagerImp Service: "
	# Run only if a Manager is not currently running in this host
        if [ ! -f $lockfile ]; then
            /usr/local/bin/acsdaemonManagerImp -o $acscbFolder/$IORFILE & 
	    # Pid File
	    echo $! > $acscbFolder/$PIDFILE
            ### Create the lock file. Remember ACS has its own Lock file for instances in /alma/ACS-<version>/acsdata/tmp/
            touch $lockfile
	else
	    warning
            echo "Service already running"
            return 0
	fi
        retval=$?
	if [ $retval -eq 0 ]; then
	    success
	    echo "acscbDaemonManagerImp started"
	else
	    failure
	    echo "Startup Failed. Check logs"	
	fi
        return $retval
}
# Stop the service
stop() {
        echo "Stopping acscbDaemonManagerImp server: "
	# If file does not exist, the process is not running. Stop does nothing
	if [ ! -f $lockfile ]; then
	    warning
	    echo "Service not running"
	    return 0   
	fi

        # if no IOR File, we call force stop
        if [ ! -f $acscbFolder/$IORFILE ]; then
            force-stop
        else
	    # In case of SIGSEV in ImpStop go to force-stop
            #acsdaemonImpStop -r $(cat "$acscbFolder/$IORFILE" ) || force-stop
	    force-stop
        fi
        # return value to check
        retval=$?
        # Clear IORFILE and PIDFILE
        echo "" > $acscbFolder/$IORFILE
        echo "" > $acscbFolder/$PIDFILE
        ### Now, delete the lock file ###
        rm -f $lockfile

	retval=$?
        if [ $retval -eq 0 ]; then
            success
            echo "acscbDaemonManagerImp stopped"
        else
            failure
            echo "Shutdown Failed. Check logs"   
        fi
        return $retval
}

force-stop() {
	# If PIDFILE Exists and has a content
	if [ -f "$acscbFolder/$PIDFILE"  ] && [ $(cat "$acscbFolder/$PIDFILE" ) ] ;then	
	    killproc -p $acscbFolder/$PIDFILE acsdaemonManagerImp
	fi
	
	retval=$?
	if [ $retval -eq 0 ]; then
            success
            echo "acscbDaemonManagerImp stopped through killproc"
        else
            failure
            echo "Stopping Failed. Check logs"   
        fi
	return $retval
}

#TODO for Complete LSB fullfilment
#reload () {
#
#}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  force-stop)
	force-stop
	;;
  status)
        status acsdaemonManagerImp
        ;;
  restart)
        stop
        start
        ;;
  reload)
	restart
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit $?
